In [1]:
#import libraries
import numpy as np
import pandas as pd

In [2]:
#dataset(Salary | Experience (Years) | Performance Score)
salary = np.array([
    [25000, 2, 80],
    [45000, 5, 90],
    [30000, 3, 75],
    [60000, 8, 95],
    [35000, 4, 85]
])

salary

array([[25000,     2,    80],
       [45000,     5,    90],
       [30000,     3,    75],
       [60000,     8,    95],
       [35000,     4,    85]])

In [3]:
#1. Average salary of all employees
average_salary = np.mean(salary[:, 0])
average_salary

np.float64(39000.0)

In [4]:
#2. Highest salary
highest_salary = np.max(salary[:, 0])
highest_salary

np.int64(60000)

In [5]:
#3. Lowest salary
lowest_salary = np.min(salary[:, 0])
lowest_salary

np.int64(25000)

In [6]:
#4. Average experience
average_experience = np.mean(salary[:, 1])
average_experience


np.float64(4.4)

In [7]:
#5. Employees with salary greater than ₹40,000
employees = salary[salary[:, 0] > 40000]
employees

array([[45000,     5,    90],
       [60000,     8,    95]])

In [8]:
#6. Employees with performance score greater than 80
employees = salary[salary[:, 2] > 80]
employees

array([[45000,     5,    90],
       [60000,     8,    95],
       [35000,     4,    85]])

In [9]:
#7. Employee with highest performance score
index = np.argmax(salary[:, 2])
employee = salary[index]
employee

array([60000,     8,    95])

In [10]:
#8. Standard deviation of salaries
salary_std = np.std(salary[:, 0])
salary_std

np.float64(12409.673645990857)

In [11]:
#9. Classify employees as High Salary or Low Salary
salary_status = np.where(
    salary[:, 0] > 40000,
    "High Salary",
    "Low Salary"
)

salary_status


array(['Low Salary', 'High Salary', 'Low Salary', 'High Salary',
       'Low Salary'], dtype='<U11')

In [12]:
#10. Convert the results into a Pandas DataFrame
df = pd.DataFrame({
    "Salary": salary[:, 0],
    "Experience": salary[:, 1],
    "Performance Score": salary[:, 2],
    "Salary Status": salary_status
})

df

,Salary,Experience,Performance Score,Salary Status
0,25000,2,80,Low Salary
1,45000,5,90,High Salary
2,30000,3,75,Low Salary
3,60000,8,95,High Salary
4,35000,4,85,Low Salary
